services:
  - type: web
    name: ithouse
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --no-input
    startCommand: gunicorn base.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: base.settings
      - key: django-insecure-7itk+u%8flx^p4)ojj5tz=u4l&e%2&(vyse@^!oovbz&n52ak2
        value: your-secret-key-here
      - key: DEBUG
        value: 'False'
