# Generated by Django 5.0.4 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_alter_profesional_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
