# Generated by Django 5.0.4 on 2025-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0003_videoupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='poster_video',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
